// { status: 200,
//   statusText: 'OK',
//   headers:
//    { server: 'ngx_openresty',
//      date: 'Mon, 02 Sep 2019 16:19:40 GMT',
//      'content-type': 'application/json;charset=UTF-8',
//      'transfer-encoding': 'chunked',
//      connection: 'close',
//      vary: 'Accept-Encoding, Accept-Encoding, accept-encoding',
//      'set-cookie': [ 'route=a6be5726af1371e4f8a76ba7cc5d77f2; Path=/' ],
//      'cache-control': 'private',
//      expires: 'Thu, 01 Jan 1970 00:00:00 GMT',
//      'x-served-by': 'ip-10-0-1-15/10.0.1.15' },
//   config:
//    { url:
//       'https://api.edamam.com/search?q=a&app_id=39bd6e33&app_key=8df8d8247d62081c03a203cfef8c7ffc',
//      headers:
//       { Accept: 'application/json, text/plain, */*',
//         'User-Agent': 'axios/0.19.0' },
//      transformRequest: [ [Function: transformRequest] ],
//      transformResponse: [ [Function: transformResponse] ],
//      timeout: 0,
//      adapter: [Function: httpAdapter],
//      xsrfCookieName: 'XSRF-TOKEN',
//      xsrfHeaderName: 'X-XSRF-TOKEN',
//      maxContentLength: -1,
//      validateStatus: [Function: validateStatus],
//      method: 'get',
//      data: undefined },
//   request:
//    ClientRequest {
//      _events:
//       { socket: [Function],
//         abort: [Function],
//         aborted: [Function],
//         error: [Function],
//         timeout: [Function],
//         prefinish: [Function: requestOnPrefinish] },
//      _eventsCount: 6,
//      _maxListeners: undefined,
//      output: [],
//      outputEncodings: [],
//      outputCallbacks: [],
//      outputSize: 0,
//      writable: true,
//      _last: true,
//      chunkedEncoding: false,
//      shouldKeepAlive: false,
//      useChunkedEncodingByDefault: false,
//      sendDate: false,
//      _removedConnection: false,
//      _removedContLen: false,
//      _removedTE: false,
//      _contentLength: 0,
//      _hasBody: true,
//      _trailer: '',
//      finished: true,
//      _headerSent: true,
//      socket:
//       TLSSocket {
//         _tlsOptions: [Object],
//         _secureEstablished: true,
//         _securePending: false,
//         _newSessionPending: false,
//         _controlReleased: true,
//         _SNICallback: null,
//         servername: 'api.edamam.com',
//         alpnProtocol: false,
//         authorized: true,
//         authorizationError: null,
//         encrypted: true,
//         _events: [Object],
//         _eventsCount: 8,
//         connecting: false,
//         _hadError: false,
//         _handle: [TLSWrap],
//         _parent: null,
//         _host: 'api.edamam.com',
//         _readableState: [ReadableState],
//         readable: true,
//         _maxListeners: undefined,
//         _writableState: [WritableState],
//         writable: false,
//         allowHalfOpen: false,
//         _sockname: null,
//         _pendingData: null,
//         _pendingEncoding: '',
//         server: undefined,
//         _server: null,
//         ssl: [TLSWrap],
//         _requestCert: true,
//         _rejectUnauthorized: true,
//         parser: null,
//         _httpMessage: [Circular],
//         [Symbol(res)]: [TLSWrap],
//         [Symbol(asyncId)]: 6,
//         [Symbol(lastWriteQueueSize)]: 0,
//         [Symbol(timeout)]: null,
//         [Symbol(kBytesRead)]: 0,
//         [Symbol(kBytesWritten)]: 0,
//         [Symbol(connect-options)]: [Object] },
//      connection:
//       TLSSocket {
//         _tlsOptions: [Object],
//         _secureEstablished: true,
//         _securePending: false,
//         _newSessionPending: false,
//         _controlReleased: true,
//         _SNICallback: null,
//         servername: 'api.edamam.com',
//         alpnProtocol: false,
//         authorized: true,
//         authorizationError: null,
//         encrypted: true,
//         _events: [Object],
//         _eventsCount: 8,
//         connecting: false,
//         _hadError: false,
//         _handle: [TLSWrap],
//         _parent: null,
//         _host: 'api.edamam.com',
//         _readableState: [ReadableState],
//         readable: true,
//         _maxListeners: undefined,
//         _writableState: [WritableState],
//         writable: false,
//         allowHalfOpen: false,
//         _sockname: null,
//         _pendingData: null,
//         _pendingEncoding: '',
//         server: undefined,
//         _server: null,
//         ssl: [TLSWrap],
//         _requestCert: true,
//         _rejectUnauthorized: true,
//         parser: null,
//         _httpMessage: [Circular],
//         [Symbol(res)]: [TLSWrap],
//         [Symbol(asyncId)]: 6,
//         [Symbol(lastWriteQueueSize)]: 0,
//         [Symbol(timeout)]: null,
//         [Symbol(kBytesRead)]: 0,
//         [Symbol(kBytesWritten)]: 0,
//         [Symbol(connect-options)]: [Object] },
//      _header:
//       'GET /search?q=a&app_id=39bd6e33&app_key=8df8d8247d62081c03a203cfef8c7ffc HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nUser-Agent: axios/0.19.0\r\nHost: api.edamam.com\r\nConnection: close\r\n\r\n',
//      _onPendingData: [Function: noopPendingOutput],
//      agent:
//       Agent {
//         _events: [Object],
//         _eventsCount: 1,
//         _maxListeners: undefined,
//         defaultPort: 443,
//         protocol: 'https:',
//         options: [Object],
//         requests: {},
//         sockets: [Object],
//         freeSockets: {},
//         keepAliveMsecs: 1000,
//         keepAlive: false,
//         maxSockets: Infinity,
//         maxFreeSockets: 256,
//         maxCachedSessions: 100,
//         _sessionCache: [Object] },
//      socketPath: undefined,
//      timeout: undefined,
//      method: 'GET',
//      path:
//       '/search?q=a&app_id=39bd6e33&app_key=8df8d8247d62081c03a203cfef8c7ffc',
//      _ended: true,
//      res:
//       IncomingMessage {
//         _readableState: [ReadableState],
//         readable: false,
//         _events: [Object],
//         _eventsCount: 3,
//         _maxListeners: undefined,
//         socket: [TLSSocket],
//         connection: [TLSSocket],
//         httpVersionMajor: 1,
//         httpVersionMinor: 1,
//         httpVersion: '1.1',
//         complete: true,
//         headers: [Object],
//         rawHeaders: [Array],
//         trailers: {},
//         rawTrailers: [],
//         aborted: false,
//         upgrade: false,
//         url: '',
//         method: null,
//         statusCode: 200,
//         statusMessage: 'OK',
//         client: [TLSSocket],
//         _consuming: false,
//         _dumped: false,
//         req: [Circular],
//         responseUrl:
//          'https://api.edamam.com/search?q=a&app_id=39bd6e33&app_key=8df8d8247d62081c03a203cfef8c7ffc',
//         redirects: [] },
//      aborted: undefined,
//      timeoutCb: null,
//      upgradeOrConnect: false,
//      parser: null,
//      maxHeadersCount: null,
//      _redirectable:
//       Writable {
//         _writableState: [WritableState],
//         writable: true,
//         _events: [Object],
//         _eventsCount: 2,
//         _maxListeners: undefined,
//         _options: [Object],
//         _redirectCount: 0,
//         _redirects: [],
//         _requestBodyLength: 0,
//         _requestBodyBuffers: [],
//         _onNativeResponse: [Function],
//         _currentRequest: [Circular],
//         _currentUrl:
//          'https://api.edamam.com/search?q=a&app_id=39bd6e33&app_key=8df8d8247d62081c03a203cfef8c7ffc' },
//      [Symbol(isCorked)]: false,
//      [Symbol(outHeadersKey)]: { accept: [Array], 'user-agent': [Array], host: [Array] } },
//   data:
//    { q: 'a',
//      from: 0,
//      to: 10,
//      params: { sane: [], q: [Array], app_key: [Array], app_id: [Array] },
//      more: false,
//      count: 0,
//      hits: [] } }